name: Vavoo Auto Update

on:
  schedule:
    - cron: '0 * * * *' # Her saat başı otomatik çalışır
  workflow_dispatch: # İstediğinde manuel başlatman için buton ekler

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install cloudscraper urllib3

      - name: Run Update Script
        env:
          MY_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          python << END
          import cloudscraper, urllib3, base64, json, unicodedata, os
          
          TOKEN = os.getenv('MY_TOKEN')
          USER = "nookjoook56-web"
          REPO = "REPO"
          FILE = "playlist.m3u"
          SOURCE = "https://raw.githubusercontent.com/nookjoook56-web/Repo/main/playlist.m3u"

          def temizle(m):
              if not m: return "Kanal"
              n = unicodedata.normalize('NFKD', str(m))
              return "".join([c for c in n if not unicodedata.combining(c)]).encode('ascii', 'ignore').decode('ascii')

          s = cloudscraper.create_scraper()
          h = urllib3.PoolManager()
          headers = {"Authorization": f"token {TOKEN}", "Accept": "application/vnd.github.v3+json"}

          res = s.get(SOURCE, timeout=30)
          ham = res.text.strip()

          if "[{\"" in ham:
              bas, son = ham.find('['), ham.rfind(']')
              channels = json.loads(ham[bas:son+1])
              out = ["#EXTM3U"]
              for ch in channels:
                  n, i = temizle(ch.get("name")), ch.get("id")
                  out.append(f'#EXTINF:-1,{n}\nhttps://vavoo.to/play/{i}/index.m3u8')
              final = "\n".join(out)
          else:
              final = f"#EXTM3U\n#EXTINF:-1, BILGI: {temizle(ham)}\nhttp://hata.url"

          api = f"https://api.github.com/repos/{USER}/{REPO}/contents/{FILE}"
          r_g = h.request('GET', api, headers=headers)
          sha = json.loads(r_g.data.decode('utf-8')).get("sha") if r_g.status == 200 else None
          
          p = {"message": "Auto Update", "content": base64.b64encode(final.encode("utf-8")).decode("utf-8")}
          if sha: p["sha"] = sha
          
          h.request('PUT', api, headers=headers, body=json.dumps(p).encode("utf-8"))
          END
